feat(remove_duplicate_lines): remove -k flag

diff --git a/remove_duplicate_lines b/remove_duplicate_lines
--- a/remove_duplicate_lines
+++ b/remove_duplicate_lines
@@ -1,22 +1,27 @@
 #!/bin/bash
 SCRIPT_NAME=${0##*/}
 
-function usage {
+function help {
   cat <<EOF
 Remove the duplicated lines from a file without chainging the order of the lines:
 Syntax: $SCRIPT_NAME [-h] filename
 Options:
     -h            print this message
-    -k            key to use to identify if a line is a duplicated line (by default we use the entire line $0)
-                  If you want to check only the first and second values of the line write  `-k $1$2`
-                      >>>>Still in TODO<<<<
 EOF
 }
 
-if [[ $1 == '-h' ]]; then
-  usage
-  exit 0
-fi
+ID='0'
+while getopts "h" option; do
+    case $option in
+        h )
+            help
+            exit 0;;
+        \?)
+            echo "Error: Invalid option"
+            exit 1;;
+    esac
+done
+shift $((OPTIND -1)) # remove all options from $#
 
-# for more details https://opensource.com/article/19/10/remove-duplicate-lines-files-awk
+# for more details https://klaudjanpepaj.com/posts/awk_the_unchained/#remove-duplicated-lines-without-changing-the-order-of-the-lines
 awk '!seen[$0]++' $1
