feat(wacom-setup): source the utils script with full path
This is needed if we want to make the script usable by other commands,
like sxhkd, which executes this command with one keybinding.

diff --git a/script_template b/script_template
--- a/script_template
+++ b/script_template
@@ -1,4 +1,16 @@
 #!/bin/bash -
+
+# In order to use the script by other commands, we have to source the file with
+# the full path
+SCRIPT_DIR="$(dirname "$(realpath "$0")")"
+if [[ -f "$SCRIPT_DIR/utils" ]]; then
+    source "$SCRIPT_DIR/utils"
+else
+    echo "Error: utils file not found in $SCRIPT_DIR"
+    exit 1
+fi
+
+
 SCRIPT_NAME=${0##*/}  # performed a string manipulation operation to get the script name
 
 function help {
diff --git a/wacom-setup b/wacom-setup
--- a/wacom-setup
+++ b/wacom-setup
@@ -1,5 +1,11 @@
 #!/bin/bash -
-source utils
+SCRIPT_DIR="$(dirname "$(realpath "$0")")"
+if [[ -f "$SCRIPT_DIR/utils" ]]; then
+    source "$SCRIPT_DIR/utils"
+else
+    echo "Error: utils file not found in $SCRIPT_DIR"
+    exit 1
+fi
 
 HAVE_INSTALLED="false"
 if ! is_installed xinput; then
