Added: `is_installed` function, validation in mp3-downlaod
`is_installed` is a function that checks if a command is present in the
PATH

diff --git a/utils b/utils
--- a/utils
+++ b/utils
@@ -4,12 +4,24 @@ export RED="\033[1;31m"
 export YELLOW="\033[1;33m"
 export NC="\033[0m" # No Color
 
-log_info (){
+function log_info {
     printf "${YELLOW}$1${NC}\n"
 }
-log_error (){
+function log_error {
     printf "${RED}$1${NC}\n"
 }
-exit_with_error (){
+function exit_with_error {
     log_error "$1" && exit 1
 }
+function is_installed {
+    [ -z "$1" ] && echo "Command name missing" && exit 1
+    COMMAND=$1
+    FOUND=false
+    # we can enhance the editor search by searching in each directory of $PATH
+    PATH_SPACED=${PATH//:/ } # separate each path by space instead of :
+    for individual_path in ${PATH_SPACED}; do
+        # true if file exist and is executable
+        [ -x "$individual_path/$COMMAND" ] && FOUND=true && break
+    done
+}
+
